/*
 * Created on 20 oct. 2014 ( Time 17:32:43 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.test.persistence;


import org.demo.bean.jpa.SubscriptionsEntity;
import org.demo.mock.SubscriptionsEntityMock;
import org.demo.persistence.PersistenceServiceProvider;
import org.demo.persistence.services.SubscriptionsPersistence;
import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Subscriptions persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class SubscriptionsPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		SubscriptionsPersistence service = PersistenceServiceProvider.getService(SubscriptionsPersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test Subscriptions persistence : delete + load ..." );
		
		SubscriptionsPersistence service = PersistenceServiceProvider.getService(SubscriptionsPersistence.class);
		
		SubscriptionsEntityMock mock = new SubscriptionsEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, "A"  );
		// process( service, mock, ... );
	}

	private void process(SubscriptionsPersistence service, SubscriptionsEntityMock mock, String email ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		SubscriptionsEntity entity = service.load( email );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( email ) ;
			Assert.assertNotNull(entity);

			// This entity references the following entities : 
			// . Events
			/* Insert only if references are OK
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );
			*/

			System.out.println(" . delete : " );
			boolean deleted = service.delete( email );
			System.out.println("   deleted = " + deleted);
		}		
	}
}
