/*
 * Created on 24 oct. 2014 ( Time 13:24:02 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.persistence.services;

import java.util.List;
import java.util.Map;

import org.demo.bean.jpa.SubscriptionsEntity;

/**
 * Basic persistence operations for entity "Subscriptions"
 * 
 * This Bean has a composite Primary Key : SubscriptionsEntityKey
 *
 * @author Telosys Tools Generator
 *
 */
public interface SubscriptionsPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param subscriptions
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(SubscriptionsEntity subscriptions) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param email
	 * @param event
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(String email, Integer event) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param subscriptions
	 */
	public void insert(SubscriptionsEntity subscriptions) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param email
	 * @param event
	 * @return the entity loaded (or null if not found)
	 */
	public SubscriptionsEntity load(String email, Integer event) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<SubscriptionsEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<SubscriptionsEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<SubscriptionsEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param subscriptions
	 * @return
	 */
	public SubscriptionsEntity save(SubscriptionsEntity subscriptions) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<SubscriptionsEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
	
}
