/*
 * Created on 24 oct. 2014 ( Time 13:24:02 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.demo.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "EVENTS"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="EVENTS", schema="APP" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="EventsEntity.countAll", query="SELECT COUNT(x) FROM EventsEntity x" )
} )
public class EventsEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="ID", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="NAME", nullable=false, length=32)
    private String     name         ;

    @Column(name="ADDRESS", nullable=false, length=128)
    private String     address      ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BEGINNING_DATE", nullable=false)
    private Date       beginningDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="END_DATE", nullable=false)
    private Date       endDate      ;

    @Column(name="PUBLISHED", nullable=false)
    private Integer    published    ;

	// "email" (column "EMAIL") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="EMAIL", referencedColumnName="EMAIL")
    private UsersEntity users       ;

    @OneToMany(mappedBy="events", targetEntity=SubscriptionsEntity.class)
    private List<SubscriptionsEntity> listOfSubscriptions;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public EventsEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NAME ( VARCHAR ) 
    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }

    //--- DATABASE MAPPING : ADDRESS ( VARCHAR ) 
    public void setAddress( String address ) {
        this.address = address;
    }
    public String getAddress() {
        return this.address;
    }

    //--- DATABASE MAPPING : BEGINNING_DATE ( TIMESTAMP ) 
    public void setBeginningDate( Date beginningDate ) {
        this.beginningDate = beginningDate;
    }
    public Date getBeginningDate() {
        return this.beginningDate;
    }

    //--- DATABASE MAPPING : END_DATE ( TIMESTAMP ) 
    public void setEndDate( Date endDate ) {
        this.endDate = endDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }

    //--- DATABASE MAPPING : PUBLISHED ( INTEGER ) 
    public void setPublished( Integer published ) {
        this.published = published;
    }
    public Integer getPublished() {
        return this.published;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setUsers( UsersEntity users ) {
        this.users = users;
    }
    public UsersEntity getUsers() {
        return this.users;
    }

    public void setListOfSubscriptions( List<SubscriptionsEntity> listOfSubscriptions ) {
        this.listOfSubscriptions = listOfSubscriptions;
    }
    public List<SubscriptionsEntity> getListOfSubscriptions() {
        return this.listOfSubscriptions;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(name);
        sb.append("|");
        sb.append(address);
        sb.append("|");
        sb.append(beginningDate);
        sb.append("|");
        sb.append(endDate);
        sb.append("|");
        sb.append(published);
        return sb.toString(); 
    } 

}
