/*
 * Created on 20 oct. 2014 ( Time 17:32:43 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.persistence.services.fake;

import java.util.List;
import java.util.Map;

import org.demo.bean.jpa.SubscriptionsEntity;
import org.demo.persistence.commons.fake.GenericFakeService;
import org.demo.persistence.services.SubscriptionsPersistence;

/**
 * Fake persistence service implementation ( entity "Subscriptions" )
 *
 * @author Telosys Tools Generator
 */
public class SubscriptionsPersistenceFAKE extends GenericFakeService<SubscriptionsEntity> implements SubscriptionsPersistence {

	public SubscriptionsPersistenceFAKE () {
		super(SubscriptionsEntity.class);
	}
	
	protected SubscriptionsEntity buildEntity(int index) {
		SubscriptionsEntity entity = new SubscriptionsEntity();
		// Init fields with mock values
		entity.setEmail( nextString() ) ;
		entity.setFirstName( nextString() ) ;
		entity.setLastName( nextString() ) ;
		entity.setCompany( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(SubscriptionsEntity entity) {
		log("delete ( SubscriptionsEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( String email ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(SubscriptionsEntity entity) {
		log("insert ( SubscriptionsEntity : " + entity + ")" ) ;
	}

	public SubscriptionsEntity load( String email ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<SubscriptionsEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<SubscriptionsEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<SubscriptionsEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public SubscriptionsEntity save(SubscriptionsEntity entity) {
		log("insert ( SubscriptionsEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<SubscriptionsEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
