
/*
 * Created on 24 oct. 2014 ( Time 13:24:02 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.mock;

import java.util.LinkedList;
import java.util.List;

import org.demo.bean.jpa.EventsEntity;
import org.demo.mock.tool.MockValues;

public class EventsEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public EventsEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public EventsEntity createInstance( Integer id ) {
		EventsEntity entity = new EventsEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setName( mockValues.nextString(32) ) ; // java.lang.String 
		entity.setAddress( mockValues.nextString(128) ) ; // java.lang.String 
		entity.setBeginningDate( mockValues.nextDate() ) ; // java.util.Date 
		entity.setEndDate( mockValues.nextDate() ) ; // java.util.Date 
		entity.setPublished( mockValues.nextInteger() ) ; // java.lang.Integer 
		// Init Link fields (if any)
		// setUsers( TODO ) ; // Users 
		// setListOfSubscriptions( TODO ) ; // List<Subscriptions> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<EventsEntity> createList(int count) {
		List<EventsEntity> list = new LinkedList<EventsEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
