
/*
 * Created on 20 oct. 2014 ( Time 17:32:43 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.mock;

import java.util.LinkedList;
import java.util.List;

import org.demo.bean.jpa.SubscriptionsEntity;
import org.demo.mock.tool.MockValues;

public class SubscriptionsEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public SubscriptionsEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextString(32) );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public SubscriptionsEntity createInstance( String email ) {
		SubscriptionsEntity entity = new SubscriptionsEntity();
		// Init Primary Key fields
		entity.setEmail( email) ;
		// Init Data fields
		entity.setFirstName( mockValues.nextString(32) ) ; // java.lang.String 
		entity.setLastName( mockValues.nextString(32) ) ; // java.lang.String 
		entity.setCompany( mockValues.nextString(32) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setEvents( TODO ) ; // Events 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<SubscriptionsEntity> createList(int count) {
		List<SubscriptionsEntity> list = new LinkedList<SubscriptionsEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
