
/*
 * Created on 24 oct. 2014 ( Time 13:24:02 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.mock;

import java.util.LinkedList;
import java.util.List;

import org.demo.bean.jpa.UsersEntity;
import org.demo.mock.tool.MockValues;

public class UsersEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public UsersEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextString(32) );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public UsersEntity createInstance( String email ) {
		UsersEntity entity = new UsersEntity();
		// Init Primary Key fields
		entity.setEmail( email) ;
		// Init Data fields
		entity.setPassword( mockValues.nextString(32) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setListOfEvents( TODO ) ; // List<Events> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<UsersEntity> createList(int count) {
		List<UsersEntity> list = new LinkedList<UsersEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
